version: 2
updates:
    - package-ecosystem: gradle
      directory: /
      schedule:
          interval: weekly
      open-pull-requests-limit: 5
      labels:
          - chore
      ignore:
          # pinned to 1.12.x for compatibility
          - dependency-name: 'io.papermc.paper:*'

    - package-ecosystem: github-actions
      directory: /
      schedule:
          interval: weekly
      open-pull-requests-limit: 5
      labels:
          - chore
