changelog:
    categories:
        - title: 🚀 New Features
          labels: [feature]
        - title: 🐛 Bug Fixes
          labels: [bug]
        - title: 🧹 Maintenance
          labels: [chore, refactor]
        - title: 📖 Documentation
          labels: [documentation]
    exclude:
        labels: [skip-changelog]
