name: RzlDiscordBot
version: '${version}'
main: com.rizzleworks.discordbot.RzlDiscordBotPlugin
description: Posts player events to Discord via webhooks
author: cliffmeyers
website: https://github.com/rizzleworks/RzlDiscordBot
api-version: '1.21'
